device: "auto"
train: # metrics that are calculated during training
  - _target_: src.metrics.SiSNRi
    device: ${metrics.device}
    name: "Si-SNRi"
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.SiSNRi
    device: ${metrics.device}
    name: "Si-SNRi"
  - _target_: src.metrics.SDRi
    device: ${metrics.device}
    name: "SDRi"
  - _target_: src.metrics.ExampleMetric
    metric:
      _target_: torchmetrics.audio.PerceptualEvaluationSpeechQuality
      fs: 16000
      mode: "nb"
    device: ${metrics.device}
    name: "PESQ"
  - _target_: src.metrics.ExampleMetric
    metric:
      _target_: torchmetrics.audio.ShortTimeObjectiveIntelligibility
      fs: 16000
    device: ${metrics.device}
    name: "STOI"
