defaults:
  - model: rtfs
  - metrics: train_eval
  - datasets: inference # we do not want to run inference on training data
  - dataloader: example
  - transforms: example_only_batch
  - _self_
inferencer:
  device_tensors: ["mix_audio", "speaker_audio", "video"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/checkpoint-epoch17.pth" # path to the pretrained model
